#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

a=1

while [ "$a" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$a" -eq 4 ]; then
    echo "bad luck"
  elif [ "$a" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((a++))
done
